### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by vishnu667** [wzrdtales/nodebb-plugin-ldap-override#1]
Hey is the plugin working 
can you post the installation instructions.

**Comment by wzrdtales** [comment]
Yes currently using it, I will add instructions for you :)

**Comment by wzrdtales** [comment]
pushed some changes not applied yet from us and some instructions, you can try if this works for you

**Comment by vishnu667** [comment]
I'm getting the following as the error

```
Error: Unknown authentication strategy "local"
    at attempt (/home/vishnu/happy/nodebb/node_modules/passport/lib/middleware/authenticate.js:173:37)
    at authenticate (/home/vishnu/happy/nodebb/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at continueLogin (/home/vishnu/happy/nodebb/src/controllers/authentication.js:189:4)
    at authenticationController.login (/home/vishnu/happy/nodebb/src/controllers/authentication.js:121:10)
    at Layer.handle [as handle_request] (/home/vishnu/happy/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vishnu/happy/nodebb/node_modules/express/lib/router/route.js:131:13)
    at /home/vishnu/happy/nodebb/src/middleware/middleware.js:262:3
    at Object.Blacklist.test (/home/vishnu/happy/nodebb/src/meta/blacklist.js:58:4)
    at middleware.applyBlacklist (/home/vishnu/happy/nodebb/src/middleware/middleware.js:261:17)
    at Layer.handle [as handle_request] (/home/vishnu/happy/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vishnu/happy/nodebb/node_modules/express/lib/router/route.js:131:13)
    at csrf (/home/vishnu/happy/nodebb/node_modules/csurf/index.js:117:5)
    at Layer.handle [as handle_request] (/home/vishnu/happy/nodebb/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/vishnu/happy/nodebb/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/vishnu/happy/nodebb/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/vishnu/happy/nodebb/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by wzrdtales** [comment]
Well with this spare amount of information I can only guess whats wrong. Maybe it does not work with your nodebb version we do have the latest one. 

The local strategy is set here https://github.com/wzrdtales/nodebb-plugin-ldap-override/blob/master/library.js#L58, thus it should register the ldapauth as the local auth strategy instead. For some reason this does not happen for you and you do not have any registered local auth at all.

Do you maybe have another plugin installed overriding the local strategy? Or do you maybe even have the wrong plugin and not the one in this repo? I have not published this whole thing to npm yet as I do not have had any time to work this thing enough out I just grabbed it and made it work yet. If you tried to get it from npm you probably have the wrong one.

**Comment by vishnu667** [comment]
No its a fresh install There is no other plugin installed

I'm testing out passport-ldapauth manually once I know that works I'll know that my configurations are right.
Then I'll start debugging on Why this is not working, and see if there is a fix

Will keep you posted
